In [14]:
import urllib.request 
from pprint import pprint
from html_table_parser import HTMLTableParser
import pandas as pd
headers={'User-Agent':'Whatever'}
def url_get_contents(url):
    req= urllib.request.Request(url=url,headers=headers)
    f=urllib.request.urlopen(req)
    return f.read()

In [15]:
xhtml=url_get_contents('https://en.climate-data.org/asia/india/hyderabad/hyderabad-2801/t/january-1/').decode('utf-8')
p=HTMLTableParser()
p.feed(xhtml)
pprint(p.tables[3])
print("\n\nPANDAS DATAFRAME\n") 
print(pd.DataFrame(p.tables[4]))
list1=[]
list2=[]
for i in range(len(p.tables[4])):
    list1.append(p.tables[4][i])
print(list1)

[['',
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December'],
 ['Avg. Temperature (°C)',
  '22.2',
  '24.8',
  '28.4',
  '31.4',
  '33.3',
  '29.8',
  '26.7',
  '26.7',
  '26.3',
  '25.9',
  '23.1',
  '21.5'],
 ['Min. Temperature (°C)',
  '15.5',
  '17.8',
  '21',
  '24.6',
  '26.8',
  '24.6',
  '22.9',
  '22.9',
  '22.2',
  '20.7',
  '17.2',
  '14.8'],
 ['Max. Temperature (°C)',
  '29',
  '31.9',
  '35.9',
  '38.2',
  '39.8',
  '35',
  '30.6',
  '30.5',
  '30.5',
  '31.1',
  '29.1',
  '28.3'],
 ['Precipitation / Rainfall (mm)',
  '4',
  '6',
  '12',
  '21',
  '32',
  '105',
  '156',
  '148',
  '175',
  '80',
  '20',
  '7']]


PANDAS DATAFRAME

              0                        1                             2  \
0                Temperature (°C) | (°F)  Temperature max. (°C) | (°F)
1    1. January            23 °C | 73 °F                 28 °C | 83 °F
2    2. January            22 °C | 72 °F                 28 °C | 83 °F
3    3. January            22 °C | 72 °F                 29 °C | 83 °F
4    4. January            22 °C | 72 °F                 29 °C | 84 °F
5    5. January            22 °C | 72 °F                 29 °C | 84 °F
6    6. January            22 °C | 72 °F                 29 °C | 84 °F
7    7. January            22 °C | 71 °F                 28 °C | 83 °F
8    8. January            22 °C | 72 °F                 29 °C | 84 °F
9    9. January            22 °C | 72 °F                 29 °C | 84 °F
10  10. January            22 °C | 72 °F                 29 °C | 84 °F
11  11. January            22 °C | 71 °F                 29 °C | 84 °F
12  12. January            22 °C | 72 °F                 29 °C | 85 °F
13  13. January            22 °C | 72 °F                 29 °C | 85 °F
14  14. January            23 °C | 73 °F                 30 °C | 86 °F
15  15. January            23 °C | 73 °F                 30 °C | 86 °F
16  16. January            23 °C | 73 °F                 30 °C | 86 °F
17  17. January            23 °C | 73 °F                 30 °C | 86 °F
18  18. January            23 °C | 73 °F                 30 °C | 86 °F
19  19. January            23 °C | 73 °F                 29 °C | 85 °F
20  20. January            23 °C | 73 °F                 30 °C | 86 °F
21  21. January            23 °C | 73 °F                 30 °C | 86 °F
22  22. January            23 °C | 74 °F                 31 °C | 87 °F
23  23. January            24 °C | 75 °F                 30 °C | 87 °F
24  24. January            24 °C | 75 °F                 30 °C | 86 °F
25  25. January            24 °C | 74 °F                 30 °C | 86 °F
26  26. January            23 °C | 74 °F                 30 °C | 86 °F
27  27. January            23 °C | 74 °F                 30 °C | 86 °F
28  28. January            23 °C | 74 °F                 30 °C | 86 °F
29  29. January            24 °C | 74 °F                 30 °C | 87 °F
30  30. January            24 °C | 75 °F                 31 °C | 87 °F
31  31. January            24 °C | 74 °F                 31 °C | 87 °F

                               3                                        4
0   Temperature min. (°C) | (°F)  Precipitation / Rainfall (mm) | (inch.)
1                  17 °C | 62 °F                       0.4 mm | 0.0 inch.
2                  16 °C | 62 °F                       0.1 mm | 0.0 inch.
3                  16 °C | 61 °F                       0.0 mm | 0.0 inch.
4                  15 °C | 59 °F                       0.0 mm | 0.0 inch.
5                  15 °C | 59 °F                       0.0 mm | 0.0 inch.
6                  15 °C | 59 °F                       0.2 mm | 0.0 inch.
7                  15 °C | 59 °F                       0.3 mm | 0.0 inch.
8                  16 °C | 60 °F                       0.0 mm | 0.0 inch.
9                  16 °C | 60 °F                       0.0 mm | 0.0 inch.
10                 15 °C | 59 °F                       0.1 mm | 0.0 inch.
11                 15 °C | 59 °F                       0.0 mm | 0.0 inch.
12                 15 °C | 59 °F                       0.0 mm | 0.0 inch.
13                 15 °C | 59 °F                       0.3 mm | 0.0 inch.
14                 15 °C | 60 °F                       0.0 mm | 0.0 inch.
15                 16 °C | 61 °F                       0.1 mm | 0.0 inch.
16                 16 °C | 60 °F                       0.0 mm | 0.0 inch.
17                 15 °C | 59 °F                       0.0 mm | 0.0 inch.
18                 16 °C | 60 °F                       0.0 mm | 0.0 inch.
19                 16 °C | 61 °F                       0.1 mm | 0.0 inch.
20                 16 °C | 61 °F                       0.0 mm | 0.0 inch.
21                 16 °C | 61 °F                       0.0 mm | 0.0 inch.
22                 16 °C | 61 °F                       0.0 mm | 0.0 inch.
23                 17 °C | 63 °F                       0.1 mm | 0.0 inch.
24                 17 °C | 63 °F                       0.0 mm | 0.0 inch.
25                 17 °C | 62 °F                       1.7 mm | 0.1 inch.
26                 17 °C | 62 °F                       0.1 mm | 0.0 inch.
27                 16 °C | 61 °F                       0.0 mm | 0.0 inch.
28                 17 °C | 62 °F                       0.6 mm | 0.0 inch.
29                 17 °C | 62 °F                       0.2 mm | 0.0 inch.
30                 17 °C | 62 °F                       0.4 mm | 0.0 inch.
31                 17 °C | 62 °F                       0.4 mm | 0.0 inch.
[['', 'Temperature (°C) | (°F)', 'Temperature max. (°C) | (°F)', 'Temperature min. (°C) | (°F)', 'Precipitation / Rainfall (mm) | (inch.)'], ['1. January', '23 °C | 73 °F', '28 °C | 83 °F', '17 °C | 62 °F', '0.4 mm | 0.0 inch.'], ['2. January', '22 °C | 72 °F', '28 °C | 83 °F', '16 °C | 62 °F', '0.1 mm | 0.0 inch.'], ['3. January', '22 °C | 72 °F', '29 °C | 83 °F', '16 °C | 61 °F', '0.0 mm | 0.0 inch.'], ['4. January', '22 °C | 72 °F', '29 °C | 84 °F', '15 °C | 59 °F', '0.0 mm | 0.0 inch.'], ['5. January', '22 °C | 72 °F', '29 °C | 84 °F', '15 °C | 59 °F', '0.0 mm | 0.0 inch.'], ['6. January', '22 °C | 72 °F', '29 °C | 84 °F', '15 °C | 59 °F', '0.2 mm | 0.0 inch.'], ['7. January', '22 °C | 71 °F', '28 °C | 83 °F', '15 °C | 59 °F', '0.3 mm | 0.0 inch.'], ['8. January', '22 °C | 72 °F', '29 °C | 84 °F', '16 °C | 60 °F', '0.0 mm | 0.0 inch.'], ['9. January', '22 °C | 72 °F', '29 °C | 84 °F', '16 °C | 60 °F', '0.0 mm | 0.0 inch.'], ['10. January', '22 °C | 72 °F', '29 °C | 84 °F', '15 °C | 59 °F', '0.1 mm | 0.0 inch.'], ['11. January', '22 °C | 71 °F', '29 °C | 84 °F', '15 °C | 59 °F', '0.0 mm | 0.0 inch.'], ['12. January', '22 °C | 72 °F', '29 °C | 85 °F', '15 °C | 59 °F', '0.0 mm | 0.0 inch.'], ['13. January', '22 °C | 72 °F', '29 °C | 85 °F', '15 °C | 59 °F', '0.3 mm | 0.0 inch.'], ['14. January', '23 °C | 73 °F', '30 °C | 86 °F', '15 °C | 60 °F', '0.0 mm | 0.0 inch.'], ['15. January', '23 °C | 73 °F', '30 °C | 86 °F', '16 °C | 61 °F', '0.1 mm | 0.0 inch.'], ['16. January', '23 °C | 73 °F', '30 °C | 86 °F', '16 °C | 60 °F', '0.0 mm | 0.0 inch.'], ['17. January', '23 °C | 73 °F', '30 °C | 86 °F', '15 °C | 59 °F', '0.0 mm | 0.0 inch.'], ['18. January', '23 °C | 73 °F', '30 °C | 86 °F', '16 °C | 60 °F', '0.0 mm | 0.0 inch.'], ['19. January', '23 °C | 73 °F', '29 °C | 85 °F', '16 °C | 61 °F', '0.1 mm | 0.0 inch.'], ['20. January', '23 °C | 73 °F', '30 °C | 86 °F', '16 °C | 61 °F', '0.0 mm | 0.0 inch.'], ['21. January', '23 °C | 73 °F', '30 °C | 86 °F', '16 °C | 61 °F', '0.0 mm | 0.0 inch.'], ['22. January', '23 °C | 74 °F', '31 °C | 87 °F', '16 °C | 61 °F', '0.0 mm | 0.0 inch.'], ['23. January', '24 °C | 75 °F', '30 °C | 87 °F', '17 °C | 63 °F', '0.1 mm | 0.0 inch.'], ['24. January', '24 °C | 75 °F', '30 °C | 86 °F', '17 °C | 63 °F', '0.0 mm | 0.0 inch.'], ['25. January', '24 °C | 74 °F', '30 °C | 86 °F', '17 °C | 62 °F', '1.7 mm | 0.1 inch.'], ['26. January', '23 °C | 74 °F', '30 °C | 86 °F', '17 °C | 62 °F', '0.1 mm | 0.0 inch.'], ['27. January', '23 °C | 74 °F', '30 °C | 86 °F', '16 °C | 61 °F', '0.0 mm | 0.0 inch.'], ['28. January', '23 °C | 74 °F', '30 °C | 86 °F', '17 °C | 62 °F', '0.6 mm | 0.0 inch.'], ['29. January', '24 °C | 74 °F', '30 °C | 87 °F', '17 °C | 62 °F', '0.2 mm | 0.0 inch.'], ['30. January', '24 °C | 75 °F', '31 °C | 87 °F', '17 °C | 62 °F', '0.4 mm | 0.0 inch.'], ['31. January', '24 °C | 74 °F', '31 °C | 87 °F', '17 °C | 62 °F', '0.4 mm | 0.0 inch.']]